; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MCUUpdater"
#define MyAppVersion GetFileVersion("ReleaseCombined\MCUUpdaterGUI.exe")
#define MyAppPublisher "DiMoon Electronics"
#define MyAppURL "https://dimoon.ru/"
#define MyAppExeName "bin/MCUUpdater.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1542FD47-DDC1-48D0-A427-181A88DD31E5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\DiMoonTools\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}_{#MyAppVersion}_setup
SolidCompression=yes
WizardStyle=modern
LicenseFile=..\LICENSE

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Files]
Source: "ReleaseCombined\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\LICENSE"; DestDir: "{app}\"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commondesktop}\MCU Updater Utility"; Filename: "{app}\bin\MCUUpdaterGUI.exe"; IconFilename: "{app}\bin\MCUUpdaterGUI.exe"
Name: "{group}\MCU Updater Utility"; Filename: "{app}\bin\MCUUpdaterGUI.exe"; WorkingDir: "{app}"

[Code]
#include "EnvPathUtils.pas"

function GetCompilerPath(): string;
begin
  Result := ExpandConstant('{app}\bin');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    AddToPath(GetCompilerPath());
  end;
end;

procedure DeinitializeUninstall();
begin
  RemoveFromPath(GetCompilerPath());
end;
